apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerapp2-workload
  namespace: default
  labels:
    app: dockerapp2
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: dockerapp2
  template:
    metadata:
      labels:
        app: dockerapp2
    spec:
      containers:
        - name: dockerapp2-container
          image: us-central1-docker.pkg.dev/csci5409-kubernetes-417610/dockerapp2/app2:VERSION_SHA
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shared-volume
              mountPath: /vishaka_PV_dir
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: k8s-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dockerapp2-service
  namespace: default
spec:
  selector:
    app: dockerapp2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000