apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /vishaka_PV_dir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

